### PR TITLE
chore: pin GitHub actions by full length SHA

### PR DESCRIPTION
**Pull request by dbelyaev**
- follow our own [recommendation](https://equinor.github.io/appsec/guidelines/gh-actions-runners/#github-actions-in-general) and pin 3rd party action by full length SHA
- add dependabot (GitHub owned) to keep actions up to date automatically (PRs will be created once a week)

### CODE REVIEW

**Comment by dbelyaev** [comment]
@larskaare @aigelonic 
please, review when you have time.

**Comment by dbelyaev** [comment]
dependabot configuration will help automate PRs such as #132 and #133.

**Comment by aigelonic** [comment]
Thanks Dmitriy!

This PR seems to do what 
* #132 
* #133 
are addressing, but more strictly following the guidelines on using SHA instead.

Do note that the guidelines also state (I have highlighted the bold part):
> Pin actions to the full length commit-hash (example "uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1). ***You can pin to a tag (version) if you trust the creator (Example: "uses: actions/checkout@v4.1.1")***

In my opinion, we should be able to trust the actions provided by GitHub themselves, in this case `actions/checkout` and `actions/setup-python`. Arguably one should also be able to trust actions by Azure, `azure/static-web-apps-deploy`.
That is, we can probably keep trusting the _tag_ syntax for these.

For dependabot - do note that when using the SHA approach, one needs to _manually_ keep the version comment in sync.
This is a tradeoff when doing the SHA-approach.

**Comment by dbelyaev** [comment]
@aigelonic I am closing this PR, as I see the point in trusting big vendors and just using latest major version.

But please, look into dependabot configuration -- this can help with maintenance of actions a lot.

**Pull request closed without merging**
